### ISSUE TITLE
Uninitialized component

### ISSUE THREAD

**Issue by FernandoTusell** [psiphi75/esp-mpu9250#7]
Please see https://esp32.com/viewtopic.php?t=21030. Your code compiled perfectly for me, but to make it run, I had to add a line
in i2c-easy.c, in function **i2c_master_init**:

esp_err_t i2c_master_init(uint8_t i2c_num, uint8_t gpio_sda, uint8_t gpio_scl)
{
  int i2c_master_port = i2c_num;
  i2c_config_t conf;
  conf.mode = I2C_MODE_MASTER;
  conf.sda_io_num = gpio_sda;
  conf.sda_pullup_en = 0;
  conf.scl_io_num = gpio_scl;
  conf.scl_pullup_en = 0;
  conf.master.clk_speed = I2C_FREQ_HZ;
  **conf.clk_flags = 0 ;   // added by  ft. 8-jun-2022**
  ESP_ERROR_CHECK(i2c_param_config(i2c_master_port, &conf));
  ESP_ERROR_CHECK(i2c_driver_install(i2c_master_port, conf.mode,I2C_RX_BUF_DISABLE, I2C_TX_BUF_DISABLE,0));
  return ESP_OK;
}

Reason is esp-idf v4.4.1, that I am using, added a new component clk_flags to the i2c_config_t object  'conf'. Probably you can make the change more elegantly, checking for esp-idf version, etc.

**Comment by psiphi75** [comment]
Hi Fernando, I've made the changes, although I haven't tested them.  It Should Just Work™.

**Comment by FernandoTusell** [comment]
Simon Werner ***@***.***> escribió:

> Hi Fernando, I've made the changes, although I haven't tested them.   
> It Should Just Work™.
>

Thank you, Simon. Not yet incorporated to my code, but it seems like the right
thing to do and that it will obviously work. Best, ft.
