### ISSUE TITLE
calibration values are lost in c++

### ISSUE THREAD

**Issue by x-labz** [psiphi75/esp-mpu9250#8]
I have discovered a strange issue: 
I've included this component in a ESP IDF C++ project, and discovered that the calibration values are lost in both 
 - [ak8963.c](https://github.com/psiphi75/esp-mpu9250/blob/master/components/mpu9250/ak8963.c) and
 - [mpu9250.c](https://github.com/psiphi75/esp-mpu9250/blob/master/components/mpu9250/mpu9250.c)

In my case modifying the declaration of  "cal" variable to static solved the issue 
like calibration_t *cal;  --> static calibration_t *cal;

Has anyone faced with this issue ?

**Comment by psiphi75** [comment]
That looks like a bug.  You can submit a PR and I'll merge it.

**Comment by psiphi75** [comment]
This is closed with #9 and #10
